#!/bin/bash
#arguments of parameters for metagenomic slurm pipeline

# Initialize variables
NAME=""
PART=""
workdir=$(pwd)/work
metadata=""
genome=""
annot=""

# Allowed environments
VALID_PART=("epyc" "defq" "jumbo" "epyc_ssd" "epyc -w f02-14")

# Validate partition
validate_partition() {
  for valid in "${VALID_PART[@]}"; do
    [[ "$1" == "$valid" ]] && return 0
  done
  return 1
}

# Help message
print_help() {
  echo "Usage: $0 --name NAME [--env ENV] [--partition PARTITION]"
  echo ""
  echo "Options:"
  echo "  -n, --name          REQUIRED: Run name or deployment name - should be unique"
  echo "  -p, --partition     REQUIRED: Avalible partition / hpc queue (epyc, defq, jumbo, epyc_ssd)"
  echo "  -m, --metadata      REQUIRED: metadata file, tsv col=sample name, col2=read1, col3=read2"
  echo "  -g, --genome        REQUIRED: genome - should be fasta file - uncompressed"
  echo "  -a, --annot         REQUIRED: annotation file gtf format file - uncompressed"
  echo "  -w, --work          Optional: working dir - default is current dir /work/"
  echo "  -h, --help          Show this help message"
  exit 0
}

# Use `getopt` to parse options
PARSED=$(getopt -o n:p:m:g:a:w:h --long name:,partition:,metdata:,genome:,annot:,work:,help -- "$@")
if [[ $? -ne 0 ]]; then
  echo "Failed to parse options." >&2
  exit 1
fi

# Reorganize the positional parameters
eval set -- "$PARSED"

# Process options
while true; do
  case "$1" in
    -n|--name) NAME="$2"; shift 2 ;;
    -w|--work)  workdir="$2"; shift 2 ;;
    -p|--partition) PART="$2"; shift 2 ;;
    -m|--metadata) metadata="$2"; shift 2 ;;
    -g|--genome) genome="$2"; shift 2 ;;
    -a|--annot) annot="$2"; shift 2 ;;
    -h|--help) print_help ;;
    --) shift; break ;;
    *) echo "Unexpected option: $1" >&2; exit 1 ;;
  esac
done

# Check if name is set (required)
if [[ -z "$NAME" ]]; then
  echo "Error: --name is required - unque run name."
  echo "Use --help for usage."
  exit 1
fi

# Check if partition is set (required)
if [[ -z "$PART" ]]; then
  echo "Error: --partition is required - define the partition / hpc queue."
  echo "Use --help for usage."
  exit 1
fi

# Check if partition is set (required)
if [[ -z "$metadata" ]]; then
  echo "Error: --metadata file is required - define your metadata."
  echo "Use --help for usage."
  exit 1
fi

# Check if genome is set (required)
if [[ -z "$genome" ]]; then
  echo "Error: --genome file is required - define your genome."
  echo "Use --help for usage."
  exit 1
fi

# Check if annotation file is set (required)
if [[ -z "$annot" ]]; then
  echo "Error: --annot file is required - define your gft annotation."
  echo "Use --help for usage."
  exit 1
fi

# Validate partition if provided
if [[ -n "$PART" ]] && ! validate_partition "$PART"; then
  echo "Error: Invalid parition '$PART'."
  echo "Allowed partitions: ${VALID_PART[*]}"
  exit 1
fi

# Output arguments
echo "Run name (unique): ${NAME}"
echo "Partition: ${PART}"
echo "Working directory: ${workdir}"
echo "Metadata file: ${metadata}"
echo "Genome file: ${genome}"
echo "Annotation file: ${annot}"

#export arguements
export NAME
export PART
export workdir
export metadata
export genome
export annot
